accounts/urls.py
from django.urls import path


urlpatterns = []

revision_commission/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('revision_commissions.urls')),  # Включение модуля urls из папки revision_commissions
    path('accounts/', include('accounts.urls')),
    # Для сброса пароля
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name="accounts/password_reset_confirm.html"), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(template_name='accounts/password_reset_complete.html'), name='password_reset_complete')
]

revision_commissions/urls.py
"""Определяет схемы URL для revision_commissions."""

from django.urls import path, include
from . import views #, api_views
from django.contrib.auth import views as auth_views
from django.urls.base import reverse_lazy
from rest_framework import routers

app_name = 'revision_commissions'

# api
''' 
router = routers.DefaultRouter()
router.register(r'users', api_views.UserViewSet)
router.register(r'organizations', api_views.OrganizationViewSet)
'''

urlpatterns = [
	# Домашняя страница
	path('', views.index, name='index'),
	# Вывод всех организаций
	path('organizations/', views.organizations, name='organizations'),
	# Страница просмотра данных организации ГУ
	path('organizations/gu/<int:organization_id>/', views.organization_gu, name='organization_gu'),
	# Страница просмотра данных организации КВАЗИ
	path('organizations/kvazi/<int:organization_id>/', views.organization_kvazi, name='organization_kvazi'),
	# Страница для создания орг
	path('new_organization/', views.new_organization_choice, name="new_organization_choice"),
	# Страница для добавления организации ГУ.
	path('new_organization/gu/', views.new_organization_gu, name='new_organization_gu'),
	# Страница для добавления организации КВАЗИ.
	path('new_organization/kvazi/', views.new_organization_kvazi, name='new_organization_kvazi'),
	# Страница для редактирования данных организации.
	path('edit_organization/<int:organization_id>/<str:type>', views.edit_organization, name='edit_organization'),
	# Страница для регистрации	
	path('register/', views.register, name="register"),
	# Страница для логина
	path('login/', views.login_view, name="login"),
	# Выход из аккаунта
	path('logout/', views.logout_view, name="logout"),
	# Для скачивания файла
	path('organizations/<int:organization_id>/download/<str:type>', views.download, name='download'),
	# Для вывода информаций об организаций в виде таблицы на вебсайте
	path('organizations/<int:organization_id>/table/<str:type>', views.table_view, name="orgnaization_info"),
	# Для удаления организаций
	path('organizations/<int:organization_id>/delete/', views.delete_organization, name="delete_organization"),
	# Показ отчетов от пользователей
	path('reports/', views.reports_view, name="reports"),
	# Вывод отчетов
	path('download_reports/', views.download_reports, name="download_reports"),
	# для сброса пароля
	path("password_reset/", views.password_reset_request, name="password_reset"),
]	

revision_commissions/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from .models import Organization_GU, Organization_KVAZI
from .forms import OrganizationGuForm, OrganizationKvaziForm, LoginForm, PasswordResetForm
from django.contrib.auth import login, authenticate, logout
from django.contrib.auth.decorators import login_required
from accounts.models import CustomUser
from accounts.forms import UserAdminCreationForm
# Create your views here.

# For files
from django.http.response import HttpResponse
#from .export import export_to_excel, generate_organization_data
#from .export2 import generate_organization_data_2
from .export_new import generate_organization_data, export_to_excel, parse_data
import os
#import mimetypes

# Сброс пароля
from django.db.models.query_utils import Q
from django.utils.http import urlsafe_base64_encode
from django.contrib.auth.tokens import default_token_generator
from django.utils.encoding import force_bytes
from django.template.loader import render_to_string
from django.core.mail import send_mail, BadHeaderError

# For combining queries
from itertools import chain


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

def index(request):
	"""Домашняя страница приложения revision_commissions"""
	return render(request, 'revision_commissions/index.html')


def organizations(request):
	"""Выводит список всех организаций"""
	
	# Если пользователь состоит в группе коммисии
	user = request.user
	if user.groups.filter(name="Commission").exists():
		organizations_gu = Organization_GU.objects.all()
		organizations_kvazi = Organization_KVAZI.objects.all()
	else:
		organizations_gu = Organization_GU.objects.filter(user_id=user.id)
		organizations_kvazi = Organization_KVAZI.objects.filter(user_id=user.id)
	
	organizations = chain(organizations_gu, organizations_kvazi)
	context = {'organizations': organizations}
	return render(request, 'revision_commissions/organizations.html', context)


@login_required
def organization_gu(request, organization_id):
	"""Выводит данные выбранной организации."""
	organization = get_object_or_404(Organization_GU, id=organization_id)
	user = request.user
	if organization.user == request.user or user.groups.filter(name="Commission").exists():
		pass
	else:
		raise Http404

	# Атрибуты
	context = {'organization': organization}
	return render(request, 'revision_commissions/organization_gu.html', context)


@login_required
def organization_kvazi(request, organization_id):
	"""Выводит данные выбранной организации."""
	organization = get_object_or_404(Organization_KVAZI, id=organization_id)
	user = request.user
	if organization.user == request.user or user.groups.filter(name="Commission").exists():
		pass
	else:
		raise Http404
	
	# Атрибуты
	context = {'organization': organization}
	return render(request, 'revision_commissions/organization_kvazi.html', context)


@login_required
def new_organization_choice(request):
	return render(request, 'revision_commissions/new_organization_choice.html')


@login_required
def new_organization_gu(request):
	"""Определяет добавление новой организации."""
	if request.method != 'POST':
		# Данные не отправлялись; создается пустая форма.
		form = OrganizationGuForm()
	else:
		# Отправлены данные POST; обработать данные.
		form = OrganizationGuForm(request.POST)
		if form.is_valid():  # Если форма допустима.
			org = form.save(commit=False)

			# for score and risk
			parsed_data = parse_data(form.cleaned_data, "ГУ")
			org.score = parsed_data[0]
			org.risk = parsed_data[1]

			org.user = request.user
			org.save()
			#cd = form.cleaned_data
			return HttpResponseRedirect(reverse('revision_commissions:organizations'))
	
	context = {'form': form, 'type': 'gu'}
	return render(request, 'revision_commissions/new_organization.html', context)


@login_required
def new_organization_kvazi(request):
	"""Определяет добавление новой организации."""
	if request.method != 'POST':
		# Данные не отправлялись; создается пустая форма.
		form = OrganizationKvaziForm()
	else:
		# Отправлены данные POST; обработать данные.
		form = OrganizationKvaziForm(request.POST)
		if form.is_valid():  # Если форма допустима.
			org = form.save(commit=False)

			parsed_data = parse_data(form.cleaned_data, "КВАЗИ")
			org.score = parsed_data[0]
			org.risk = parsed_data[1]
			
			org.user = request.user
			org.save()
			#cd = form.cleaned_data
			return HttpResponseRedirect(reverse('revision_commissions:organizations'))
	
	context = {'form': form, 'type': 'kvazi'}
	return render(request, 'revision_commissions/new_organization.html', context)


@login_required
def edit_organization(request, organization_id, type):
	"""Редактирует данные организации."""
	if type == "ГУ":
		organization = get_object_or_404(Organization_GU, id=organization_id)
		if organization.user != request.user:
			raise Http404
		
		if request.method != 'POST':
			# Форма заполняется данными текущей организации.
			form = OrganizationGuForm(instance=organization)
		else:
			# Отправка данных POST; обработать данные.
			form = OrganizationGuForm(instance=organization, data=request.POST)
			if form.is_valid():
				form.save()
				return HttpResponseRedirect(reverse(
								'revision_commissions:organization_gu',
													args=[organization.id]))
	elif type == "КВАЗИ":
		organization = get_object_or_404(Organization_KVAZI, id=organization_id)
		if organization.user != request.user:
			raise Http404
		
		if request.method != 'POST':
			# Форма заполняется данными текущей организации.
			form = OrganizationKvaziForm(instance=organization)
		else:
			# Отправка данных POST; обработать данные.
			form = OrganizationKvaziForm(instance=organization, data=request.POST)
			if form.is_valid():
				form.save()
				return HttpResponseRedirect(reverse(
								'revision_commissions:organization_kvazi',
													args=[organization.id]))
	
	context = {'form': form, 'organization': organization}
	return render(request, 'revision_commissions/edit_organization.html', context)


def delete_organization(request, organization_id):
	organization = Organization.objects.get(id=organization_id)
	if organization.user == request.user or request.user.groups.filter(name="Commission").exists():
		organization.delete()
	return HttpResponseRedirect(reverse('revision_commissions:organizations'))


def register(request):
	# Регистрация пользователя
	if request.method != 'POST':
		form = UserAdminCreationForm()
	# if request = post
	else:
		form = UserAdminCreationForm(request.POST)
		if form.is_valid():
			form.save()
			'''
			cd = form.cleaned_data
			email = cd.get("email")
			password = cd.get("password")
			user = authenticate(email=email, password=password)
			login(request, user)
			'''
			return HttpResponseRedirect(reverse('revision_commissions:login'))
	
	context = {'form': form}
	return render(request, "revision_commissions/register.html", context)


def login_view(request):
	# Логин
	if request.method != 'POST':
		form = LoginForm()
	else:
		form = LoginForm(request.POST)
		if form.is_valid():
			cd = form.cleaned_data
			email = cd.get('email')
			password = cd.get('password')
			user = authenticate(request, username=email, password=password)
			if user is not None:
				login(request, user)
				return HttpResponseRedirect(reverse('revision_commissions:new_organization_choice'))
			else:
				context = {'form': form}
				return render(request, "revision_commissions/login.html", context)
	
	context = {'form': form}
	return render(request, "revision_commissions/login.html", context)


def logout_view(request):
	logout(request)
	return HttpResponseRedirect(reverse('revision_commissions:organizations'))


# For downloading the excel
@login_required
def download(request, organization_id, type):
	if type == "ГУ":
		org = Organization_GU.objects.get(id=organization_id)
		# Скачать может только пользователь создавший пост или из группы коммиссий
		if org.user == request.user or request.user.groups.filter(name="Commission").exists():
			arr = [
					org.annualFunding,
					org.finPrePeriod,
					org.finCurPeriod,
					org.finEndYear,
					org.cashExpense,
					org.dateLastCheck,
					org.dateReport,
					org.finViolations,
					org.volRecoverFin,
					org.volReceivableCurrent,
					org.volReceivablePrevious,
					org.payableCurrent,
					org.payablePrevious,
					org.illegalActions,
					org.disciplineSanctions,
					org.materialEthics,
					org.employeeEthics,
					org.administrativeMeasures,
					org.disciplineMeasures,
					org.firedViolation
				]
			data = generate_organization_data(arr, "ГУ")
		else:
			context = {'organization': org}
			return render(request, 'revision_commissions/organization.html', context)
	elif type == "КВАЗИ":
		org = Organization_KVAZI.objects.get(id=organization_id)
		if org.user == request.user or request.user.groups.filter(name="Commission").exists():
			arr = [
				org.annualFunding,
				org.finEndYear,
				org.cashExpense,
				org.dateLastCheck,
				org.dateReport,
				org.finViolations,
				org.volRecoverFin,
				org.volReceivableCurrent,
				org.volReceivablePrevious,
				org.payableCurrent,
				org.payablePrevious,
				org.illegalActions,
				org.disciplineSanctions,
				org.employeeEthics,
				org.administrativeMeasures,
				org.disciplineMeasures,
				org.firedViolation,
				org.volAuthorizedCapitalCurrent,
				org.volAuthorizedCapitalPrevious,
				org.volIncomeCurrent,
				org.volIncomePrevious,
				org.volDividentsCurrent,
				org.volAdministrativeSpendings,
			]
			data = generate_organization_data(arr, "КВАЗИ")
		else:
			context = {'organization': org}
			return render(request, 'revision_commissions/organization.html', context)

	import re
	'''Если в названии будут кавычки убирает их, иначе ошибка'''
	namesRegex = re.compile(r'"')  # Искать кавычки
	orgName = namesRegex.sub('', org.name)  # Заменить кавычки на ''
	data.insert(0, ["Наименование критерия", "Значение", "Балл"])

revision_commissions/templates/revision_commissions/base2.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <link
      rel="stylesheet"
      href="{% static 'revision_commissions/css/bootstrap.css' %}"
    />
      <script src="{% static 'revision_commissions/js/bootstrap.min.js' %}"></script>
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
    <title>Ревизионная комиссия</title>
  </head>
  <body>

  <!-- FIRST NAV -->
  <nav class="navbar navbar-dark py-3" style="background-color: #1f3c88;">
  <div class="container-fluid col-md-10 col-md-offset-1">
    <a class="navbar-brand" href="{% url 'revision_commissions:index' %}">
      <div class="row ">
        <img src="{% static 'revision_commissions/images/gerb.png' %}" alt="" width="75" height="75" class="d-inline-block align-text-top">
        <p class="h3 p-3">Ревизионная комиссия Байзакского района</p>
      </div>
    </a>
  </div>
</nav>
<!-- END OF FIRST NAV -->
	
<hr style="background-color: #4c64a0; margin:0px">
<!-- ACTUAL NAVIGATIONG BAR NOW -->
<nav class="navbar navbar-expand-lg navbar-dark " style="background-color: #1f3c88;">
  <div class="container-fluid col-md-10 col-md-offset-1">

    <!-- Toggler/collapsibe Button -->
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav">
      <span class="navbar-toggler-icon"></span>
    </button>


    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link" aria-current="page" href="{% url 'revision_commissions:organizations' %}">Организации</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'revision_commissions:reports' %}">Отчеты</a>
        </li>

      </ul>
      <!-- Login/register -->
      <ul class="nav navbar-nav ml-auto">
        <!-- Если пользователь в аккаунте -->
            {% if request.user.is_authenticated %}
            <li class="nav-item">
              <a class="nav-link"
                >{{ user.first_name }}
                </a>
            </li>
            <li class="nav-item">
              <a
                class="btn btn-danger"
                href="{% url 'revision_commissions:logout' %}"
                >Выход</a
              >
            </li>

            {% else %}
            <li class="nav-item">
              <a
                class="btn btn-outline-success"
                href="{% url 'revision_commissions:register' %}"
                >Регистрация</a
              >
            </li>
            <li class="nav-item">
              <a
                class="btn btn-primary"
                href="{% url 'revision_commissions:login' %}"
                >Вход</a
              >
            </li>
            {% endif %}
      </ul>
      <!-- END of login -->
    </div>
  </div>
</nav>
<!--END OF SECOND Navbar-->
<div class="container-fluid col-md-10 col-md-offset-1">
</div>
  <div>
    {% block content %}
    {% endblock %}
  </div>
  </body>

</footer>
</html>

revision_commissions/templates/revision_commissions/edit_organization.html
{% extends 'revision_commissions/base2.html' %}

{% load crispy_forms_tags %}

{% block content %}
<!-- Centering div -->
<div class="container-fluid col-md-10 col-md-offset-1">

  <h5 class="m-4">Редактирование данных:</h5>
  
  <form action="{% url 'revision_commissions:edit_organization' organization.id organization.type %}" method='post'>
    {% csrf_token %}
	{{ form|crispy }}
		<div class="form-group m-4">
        	<input class="btn btn-primary" type="submit" value="Добавить">
    	</div>
  </form>

  	<!-- ERROR MESSAGES -->
	{% if form.errors %}
		{% for field in form %}
			{% for error in field.errors %}
				<div class="alert alert-danger">
					<strong>{{ error|escape }}</strong>
				</div>
			{% endfor %}
		{% endfor %}
		{% for error in form.non_field_errors %}
			<div class="alert alert-danger">
				<strong>{{ error|escape }}</strong>
			</div>
		{% endfor %}
	{% endif %}
	<!-- END -->
</div>
{% endblock content %}

revision_commissions/templates/revision_commissions/new_organization.html
{% extends "revision_commissions/base2.html" %}
{% load static %}

<!-- FORMS -->
{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid col-md-10 col-md-offset-1">
	<h5 class="m-4">Добавление организации:</h5>
	{% if type == "gu" %}
	<form action="{% url 'revision_commissions:new_organization_gu' %}" method='post'>
		{% csrf_token %}
		{{ form|crispy }}
		<div class="form-group m-4">
        	<input class="btn btn-primary" type="submit" value="Добавить">
    	</div>
	</form>

	{% elif type == "kvazi" %}
	<form action="{% url 'revision_commissions:new_organization_kvazi' %}" method='post'>
		{% csrf_token %}
		{{ form|crispy }}
		<div class="form-group m-4">
        	<input class="btn btn-primary" type="submit" value="Добавить">
    	</div>
	</form>

	{% endif %}

	<!-- ERROR MESSAGES -->
	{% if form.errors %}
		{% for field in form %}
			{% for error in field.errors %}
				<div class="alert alert-danger">
					<strong>{{ error|escape }}</strong>
				</div>
			{% endfor %}
		{% endfor %}
		{% for error in form.non_field_errors %}
			<div class="alert alert-danger">
				<strong>{{ error|escape }}</strong>
			</div>
		{% endfor %}
	{% endif %}
	<!-- END -->

<script src="{% static 'revision_commissions/js/duplicate.js' %}"></script>
</div>
{% endblock content %}

revision_commissions/templates/revision_commissions/new_organization_choice.html
{% extends "revision_commissions/base2.html" %}

<!-- FORMS -->
{% load crispy_forms_tags %}

{% block content %}
<div class="container-fluid col-md-10 col-md-offset-1">
	<a href="{% url 'revision_commissions:new_organization_gu' %}" class="btn btn-outline-primary m-4">Добавить организацию ГУ</a>
    <a href="{% url 'revision_commissions:new_organization_kvazi' %}" class="btn btn-outline-primary m-4">Добавить организацию КВАЗИ</a>
</div>
{% endblock content %}

revision_commissions/templates/revision_commissions/organization_gu.html
{% extends 'revision_commissions/base2.html' %} 

{% block content %}
<div class="container-fluid col-md-10 col-md-offset-1">

<div class="card">
  <h5 class="card-header">Данные организации:</h5>
  <div class="card-body">

    <p class="card-title fw-bold">
      <b>Наименование организации:</b> {{ organization.name }}
    </p>

    <p class="card-title fw-bold">
      <b>Годовой объем финансирования учреждения:</b> {{ organization.annualFunding.normalize }}
    </p>
    <p class="card-title fw-bold">
      <b>Объем финансирования прошлого периода:</b> {{ organization.finPrePeriod.normalize }}
    </p>
    <p class="card-title fw-bold">
      <b>Объем финансирования текущего периода:</b> {{ organization.finCurPeriod.normalize }}
    </p>
    <p class="card-title fw-bold">
      <b>Объем финансирования на конец финансового года:</b> {{ organization.finEndYear.normalize }}
    </p>
    <p class="card-title fw-bold">
      <b
        >Кассовый расход(исполнение плаченных обязательств по бюджетным
        программам (подпрограммам):</b
      >
      {{ organization.cashExpense.normalize }}
    </p>
    <p class="card-title fw-bold">
      <b>Дата проведения последней проверки:</b> {{ organization.dateLastCheck|date:"m.d.Y" }}
    </p>
    <p class="card-title fw-bold">
      <b>Фактическая дата на конец отчетного периода:</b> {{ organization.dateReport|date:"m.d.Y" }}
    </p>
    <p class="card-title fw-bold">
      <b>Объем выявленных финансовых нарушений:</b> {{ organization.finViolations.normalize }}
    </p>
    <p class="card-title fw-bold">
      <b>Объем востановленных/возмещенных средств:</b> {{ organization.volRecoverFin.normalize }}
    </p>
    <p class="card-title fw-bold">
      <b>Объем дебиторской задолженности текущего периода:</b> {{ organization.volReceivableCurrent.normalize }}
    </p>
    <p class="card-title fw-bold">
      <b>Объем дебиторской задолженности прошлого периода:</b> {{ organization.volReceivablePrevious.normalize }}
    </p>
    <p class="card-title fw-bold">
      <b>Объем кредиторской задолженности текущего периода:</b> {{ organization.payableCurrent.normalize }}
    </p>
    <p class="card-title fw-bold">
      <b>Объем кредиторской задолженности прошлого периода:</b> {{ organization.payablePrevious.normalize }}
    </p>

    <p class="card-title fw-bold">
      <b>Коррупционные и уголовные действия при освоении бюджетных средств: </b> {{ organization.illegalActions }}
    </p>

    <p class="card-title fw-bold">
      <b>Дисциплинарные взыскания, дискредитирующие государственную службу: </b> {{ organization.disciplineSanctions }}
    </p>

    <p class="card-title fw-bold">
      <b>Количество материалов рассмотренных советом по этике: </b> {{ organization.materialEthics }}
    </p>

    <p class="card-title fw-bold">
      <b>Количество сотрудников, привлеченных к дисциплинарной ответственности советом по этике: </b> {{ organization.employeeEthics }}
    </p>

    <p class="card-title fw-bold">
      <b>Административные меры в результате выявленных нарушений по государственным закупкам: </b> {{ organization.administrativeMeasures }}
    </p>

    <p class="card-title fw-bold">
      <b>Дисциплинарные меры в результате выявленных нарушений по государственным закупкам: </b> {{ organization.disciplineMeasures }}
    </p>

    <p class="card-title fw-bold">
      <b>Увольнение в результате выявленных нарушений по государственным закупкам: </b> {{ organization.firedViolation }}
    </p>

    <div class="d-flex flex-row">
      <a
        href="{% url 'revision_commissions:edit_organization' organization_id=organization.id type=organization.type %}"
        class="btn btn-outline-primary m-4"
        >Редактировать</a
      >

      <a
        href="{% url 'revision_commissions:orgnaization_info' organization.id organization.type %}"
        class="btn btn-outline-primary m-4"
        >Таблица</a
      >
      </div>
  </div>
</div>
</div>
{% endblock content %}

revision_commissions/templates/revision_commissions/organization_kvazi.html
{% extends 'revision_commissions/base2.html' %} 

{% block content %}
<div class="container-fluid col-md-10 col-md-offset-1">

<div class="card">
  <h5 class="card-header">Данные организации:</h5>
  <div class="card-body">

    <p class="card-title fw-bold">
      <b>Наименование организации:</b> {{ organization.name }}
    </p>

    <p class="card-title fw-bold">
      <b>Годовой объем финансирования учреждения:</b> {{ organization.annualFunding.normalize }}
    </p>
    <p class="card-title fw-bold">
      <b>Объем финансирования на конец финансового года:</b> {{ organization.finEndYear.normalize }}
    </p>
    <p class="card-title fw-bold">
      <b
        >Кассовый расход(исполнение плаченных обязательств по бюджетным
        программам (подпрограммам):</b
      >
      {{ organization.cashExpense.normalize }}
    </p>
    <p class="card-title fw-bold">
      <b>Дата проведения последней проверки:</b> {{ organization.dateLastCheck|date:"m.d.Y" }}
    </p>
    <p class="card-title fw-bold">
      <b>Фактическая дата на конец отчетного периода:</b> {{ organization.dateReport|date:"m.d.Y" }}
    </p>
    <p class="card-title fw-bold">
      <b>Объем выявленных финансовых нарушений:</b> {{ organization.finViolations.normalize }}
    </p>
    <p class="card-title fw-bold">
      <b>Объем востановленных/возмещенных средств:</b> {{ organization.volRecoverFin.normalize }}
    </p>
    <p class="card-title fw-bold">
      <b>Объем дебиторской задолженности текущего периода:</b> {{ organization.volReceivableCurrent.normalize }}
    </p>
    <p class="card-title fw-bold">
      <b>Объем дебиторской задолженности прошлого периода:</b> {{ organization.volReceivablePrevious.normalize }}
    </p>
    <p class="card-title fw-bold">
      <b>Объем кредиторской задолженности текущего периода:</b> {{ organization.payableCurrent.normalize }}
    </p>
    <p class="card-title fw-bold">
      <b>Объем кредиторской задолженности прошлого периода:</b> {{ organization.payablePrevious.normalize }}
    </p>

    <p class="card-title fw-bold">
      <b>Коррупционные и уголовные действия при освоении бюджетных средств: </b> {{ organization.illegalActions }}
    </p>

    <p class="card-title fw-bold">
      <b>Дисциплинарные взыскания, дискредитирующие государственную службу: </b> {{ organization.disciplineSanctions }}
    </p>

    <p class="card-title fw-bold">
      <b>Количество сотрудников, привлеченных к дисциплинарной ответственности советом по этике: </b> {{ organization.employeeEthics }}
    </p>

    <p class="card-title fw-bold">
      <b>Административные меры в результате выявленных нарушений по государственным закупкам: </b> {{ organization.administrativeMeasures }}
    </p>

    <p class="card-title fw-bold">
      <b>Дисциплинарные меры в результате выявленных нарушений по государственным закупкам: </b> {{ organization.disciplineMeasures }}
    </p>

    <p class="card-title fw-bold">
      <b>Увольнение в результате выявленных нарушений по государственным закупкам: </b> {{ organization.firedViolation }}
    </p>

    <p class="card-title fw-bold">
      <b>Объем уставного капитала текущего периода: </b> {{ organization.volAuthorizedCapitalCurrent.normalize }}
    </p>

    <p class="card-title fw-bold">
      <b>Объем уставного капитала прошлого периода: </b> {{ organization.volAuthorizedCapitalPrevious.normalize }}
    </p>

    <p class="card-title fw-bold">
      <b>Объем чистой прибыли текущего периода: </b> {{ organization.volIncomeCurrent.normalize }}
    </p>

    <p class="card-title fw-bold">
      <b>Объем чистой прибыли прошлого периода: </b> {{ organization.volIncomePrevious.normalize }}
    </p>

    <p class="card-title fw-bold">
      <b>Объем дивидендов текущего периода: </b> {{ organization.volDividentsCurrent.normalize }}
    </p>

    <p class="card-title fw-bold">
      <b>Объем административных расходов текущего периода: </b> {{ organization.volAdministrativeSpendings.normalize }}
    </p>

    <div class="d-flex flex-row">
      <a
        href="{% url 'revision_commissions:edit_organization' organization.id organization.type %}"
        class="btn btn-outline-primary m-4"
        >Редактировать</a
      >

      <a
        href="{% url 'revision_commissions:orgnaization_info' organization.id organization.type %}"
        class="btn btn-outline-primary m-4"
        >Таблица</a
      >
      </div>
  </div>
</div>
</div>
{% endblock content %}